// <auto-generated> Generated from SceneListConfigSchema asset. Do not edit. </auto-generated>
using Eflatun.SceneReference;
using Quantum;
using QuantumUser.View;
public static class SceneList
{
    public static readonly SceneInfo MenuPrototype = new SceneInfo {
        scene = new SceneReference("21e27de20aca94240b1bcad8cc23e615"),
        hasRuntimeConfig = false,
    };
    public static readonly SceneInfo MultiplayPrototype = new SceneInfo {
        scene = new SceneReference("11cad2fe964a0424a84a5c9c3bfdb9e9"),
        hasRuntimeConfig = true,
        runtimeConfig = new RuntimeConfig {
            Map = new AssetGuid(363481078872077106),
            SimulationConfig = new AssetGuid(163983649200099817),
            SystemsConfig = new AssetGuid(378553162747903325)
        },
    };

    public static readonly SceneInfo[] All = { MenuPrototype, MultiplayPrototype };
}
