using Quantum;
using Yggdrasill.Utilities;

namespace Yggdrasill.Editor
{
    // Assets/Scripts/Editor/SceneCodeGenerator.cs
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using UnityEditor;
    using UnityEngine;

    public static class SceneListManager
    {
        private const string SceneListCodeOutputPath = "Assets/Scripts/Utilities/SceneList.g.cs";
        private const string SceneIdCodeOutputPath = "Assets/Scripts/TestHelper/Protocol/SceneId.g.cs";
        private const string QuantumMenuSceneAssetOutputDir = "Assets/Resources/Maps/";

        /// <summary>
        /// <see cref="SceneListConfigSchema"/> 에셋의 데이터를 기반으로 다음을 수행한다. <br/>
        /// 1. SceneId 열거형 코드 생성 <br/>
        /// 2. SceneList 클래스 코드 생성 <br/>
        /// 3. QuantumMenuSceneInfo 에셋 생성 <br/>
        /// 4. 에디터 build profiles의 씬 목록 작성
        /// </summary>
        /// <remarks>
        /// SceneList 클래스는 정적 상수를 통해, 씬의 존재를 컴파일 타임에 보장해 주는 용도이다.
        /// <see cref="SceneListConfigSchema"/>는 프로젝트 내에 정확히 하나 존재해야 한다. 그렇지 않으면, 이 메서드는 에러 로그를 출력한 뒤 아무 작업도 수행하지 않는다.
        /// </remarks>
        [MenuItem("Tools/Scenes/Generate Scene List")]
        public static void Generate()
        {
            var list = FindList();
            if (list == null)
                return;

            if (!list.Validate())
                return;

            WriteFile(list);
            WriteSceneIdFile(list);
            GenerateQuantumMenuSceneInfos(list);
            SetBuildProfilesSceneList(list);
        }

        /// <summary>
        /// 에셋 데이터베이스의 유일한 <see cref="SceneListConfigSchema"/> 에셋을 찾아 반환한다.
        /// </summary>
        /// <remarks>
        /// 에셋 데이터베이스 내에 <see cref="SceneListConfigSchema"/> 에셋이 존재하지 않거나, 2개 이상인 경우, 에러 로그를 출력하고 null을 반환한다.
        /// </remarks>
        private static SceneListConfigSchema? FindList()
        {
            var guids = AssetDatabase.FindAssets("t:SceneListConfigSchema");

            SceneListConfigSchema? result = null;
            if (guids.Length == 0)
                Debug.LogError("SceneListConfigSchema asset를 찾을 수 없습니다.");
            else if (guids.Length != 1)
                Debug.LogError($"SceneListConfigSchema asset가 1개 이상 존재합니다. ({guids.Length}개)");
            else
                result = AssetDatabase.LoadAssetAtPath<SceneListConfigSchema>(AssetDatabase.GUIDToAssetPath(guids[0]));

            return result;
        }

        /// <summary>
        /// <see cref="list"/>에 대응하는 SceneList 클래스 코드를 작성한다.
        /// </summary>
        private static void WriteFile(SceneListConfigSchema list)
        {
            var sb = new StringBuilder();
            sb.AppendLine(
                "// <auto-generated> Generated from SceneListConfigSchema asset. Do not edit. </auto-generated>");
            sb.AppendLine("using Eflatun.SceneReference;");
            sb.AppendLine("using Quantum;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Yggdrasill.TestHooks.Protocol;");
            sb.AppendLine();
            sb.AppendLine("namespace Yggdrasill.Utilities");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SceneList");
            sb.AppendLine("    {");

            foreach (var sceneInfo in list.scenes)
            {
                var id = Sanitize(sceneInfo.scene.Name);
                var json = JsonUtility.ToJson(sceneInfo);
                json = json.Replace("\"", "\"\"");
                sb.AppendLine(
                    $"        public static readonly SceneInfo {id} = " +
                    $"JsonUtility.FromJson<SceneInfo>(@\"{json}\");"
                );
            }


            sb.AppendLine();
            sb.Append("        public static readonly SceneInfo[] All = { ");
            sb.Append(string.Join(", ", list.scenes.Select(sceneInfo => Sanitize(sceneInfo.scene.Name))));
            sb.AppendLine(" };");

            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 씬 식별자에 대응하는 씬 정보를 반환한다.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static SceneInfo Get(SceneId sceneId) => sceneId switch");
            sb.AppendLine("        {");
            foreach (var sceneInfo in list.scenes)
            {
                var id = Sanitize(sceneInfo.scene.Name);
                sb.AppendLine($"            SceneId.{id} => {id},");
            }
            sb.AppendLine("            _ => throw new System.ArgumentOutOfRangeException(nameof(sceneId)),");
            sb.AppendLine("        };");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(SceneListCodeOutputPath)!);
            File.WriteAllText(SceneListCodeOutputPath, sb.ToString());

            Debug.Log($"Scenes.g.cs 생성 완료 ({list.scenes.Length} scenes).");
        }

        /// <summary>
        /// <see cref="list"/>에 대응하는 SceneId 열거형 코드를 작성한다.
        /// </summary>
        /// <remarks>
        /// SceneList와 달리 유니티 타입을 일절 참조하지 않는다.
        /// 유니티 밖(예: 별도 프로세스로 게임을 조작하는 테스트 드라이버)에서도 씬을 컴파일 타임에 안전하게 지목할 수 있도록 하기 위함이다.
        /// </remarks>
        private static void WriteSceneIdFile(SceneListConfigSchema list)
        {
            var sb = new StringBuilder();
            sb.AppendLine(
                "// <auto-generated> Generated from SceneListConfigSchema asset. Do not edit. </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace Yggdrasill.TestHooks.Protocol");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 씬의 식별자.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum SceneId");
            sb.AppendLine("    {");

            foreach (var sceneInfo in list.scenes)
                sb.AppendLine($"        {Sanitize(sceneInfo.scene.Name)},");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(SceneIdCodeOutputPath)!);
            File.WriteAllText(SceneIdCodeOutputPath, sb.ToString());

            Debug.Log($"SceneId.g.cs 생성 완료 ({list.scenes.Length} scenes).");
        }

        /// <summary>
        /// <see cref="name"/> 이 유효한 C# 식별자가 되도록 정규화된 결과를 반환한다.
        /// </summary>
        /// <remarks>
        /// 예: "Main Menu" -> "Main_Menu"
        /// </remarks>
        private static string Sanitize(string name)
        {
            // 영문자와 숫자를 제외한 모든 문자를 "_"로 교체
            var id = Regex.Replace(name, @"[^0-9A-Za-z_]", "_");

            if (id.Length == 0 || char.IsDigit(id[0])) id = "_" + id;
            return id;
        }

        /// <summary>
        /// <see cref="list"/> 내 <see cref="SceneInfo.hasRuntimeConfig"/>가 true인 씬에 대해 <see cref="QuantumMenuSceneInfo"/> 에셋을 생성/갱신한다.
        /// </summary>
        private static void GenerateQuantumMenuSceneInfos(SceneListConfigSchema list)
        {
            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (var sceneInfo in list.scenes.Where(sceneInfo => sceneInfo.hasRuntimeConfig))
                {
                    GenerateQuantumMenuSceneInfo(sceneInfo);
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"QuantumMenuSceneInfo 에셋 생성/갱신 완료");
        }

        /// <summary>
        /// <see cref="QuantumMenuSceneAssetOutputDir"/>에 <see cref="sceneInfo"/>에 대응하는 <see cref="QuantumMenuSceneInfo"/> 에셋을 생성한다.
        /// 에셋이 이미 존재하는 경우, 기존 에셋을 갱신한다.
        /// </summary>
        /// <param name="sceneInfo"></param>
        private static void GenerateQuantumMenuSceneInfo(SceneInfo sceneInfo)
        {
            string assetPath = QuantumMenuSceneAssetOutputDir + sceneInfo.scene.Name + "_QuantumMenuSceneInfo.asset";
            var oldAsset = AssetDatabase.LoadAssetAtPath<QuantumMenuSceneInfo>(assetPath);
            
            QuantumMenuSceneInfo quantumMenuSceneAsset;
            if (oldAsset == null)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(assetPath)!);
                quantumMenuSceneAsset = ScriptableObject.CreateInstance<QuantumMenuSceneInfo>();
            }
            else
            {
                quantumMenuSceneAsset = oldAsset;
            }

            sceneInfo.SyncQuantumMenuSceneInfo(quantumMenuSceneAsset);

            if (oldAsset == null)
                AssetDatabase.CreateAsset(quantumMenuSceneAsset, assetPath);
            else
                EditorUtility.SetDirty(quantumMenuSceneAsset);
        }
        
        /// <summary>
        /// 에디터 build profiles의 씬 목록을 <see cref="list"/>에 맞게 갱신한다.
        /// </summary>
        private static void SetBuildProfilesSceneList(SceneListConfigSchema list)
        {
            EditorBuildSettings.scenes = list.scenes.Select(sceneInfo => new EditorBuildSettingsScene(sceneInfo.scene.Path, true)).ToArray();
            Debug.Log("Build Profiles 씬 설정 완료.");
        }

    }
    
    
}