namespace Editor
{
    // Assets/Scripts/Editor/SceneCodeGenerator.cs
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using UnityEditor;
    using UnityEngine;

    public static class SceneListManager
    {
        // 생성물은 Runtime asmdef 폴더에 둬서 게임/테스트 코드가 모두 참조 가능
        private const string OutputPath = "Assets/QuantumUser/View/SceneList.g.cs";

        public static void Generate()
        {
            var list = FindList();
            if (list == null)
                return;

            WriteFile(list);
            Debug.Log($"Scenes.g.cs 생성 완료 ({list.scenes.Length} scenes).");
        }

        private static SceneListConfigSchema? FindList()
        {
            var guids = AssetDatabase.FindAssets("t:SceneListConfigSchema");

            SceneListConfigSchema? result = null;
            if (guids.Length == 0)
                Debug.LogError("SceneListConfigSchema asset를 찾을 수 없습니다.");
            else if (guids.Length != 1)
                Debug.LogError($"SceneListConfigSchema asset가 1개 이상 존재합니다. ({guids.Length}개)");
            else
                result = AssetDatabase.LoadAssetAtPath<SceneListConfigSchema>(AssetDatabase.GUIDToAssetPath(guids[0]));

            return result;
        }

        private static void WriteFile(SceneListConfigSchema list)
        {
            var sb = new StringBuilder();
            sb.AppendLine(
                "// <auto-generated> Generated from SceneListConfigSchema asset. Do not edit. </auto-generated>");
            sb.AppendLine("using Eflatun.SceneReference;");
            sb.AppendLine("using Quantum;");
            sb.AppendLine("using QuantumUser.View;");
            sb.AppendLine("using UnityEngine;");

            sb.AppendLine("public static class SceneList");
            sb.AppendLine("{");

            foreach (var sceneInfo in list.scenes)
            {
                var id = Sanitize(sceneInfo.scene.Name);
                var json = JsonUtility.ToJson(sceneInfo);
                json = json.Replace("\"", "\"\"");
                sb.AppendLine(
                    $"    public static readonly SceneInfo {id} = " +
                    $"JsonUtility.FromJson<SceneInfo>(@\"{json}\");"
                );
            }


            sb.AppendLine();
            sb.Append("    public static readonly SceneInfo[] All = { ");
            sb.Append(string.Join(", ", list.scenes.Select(sceneInfo => Sanitize(sceneInfo.scene.Name))));
            sb.AppendLine(" };");

            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(OutputPath)!);
            File.WriteAllText(OutputPath, sb.ToString());
        }

        // 씬 이름이 유효한 C# 식별자가 아닐 수 있으므로 정규화 ("Main Menu" -> "Main_Menu")
        private static string Sanitize(string name)
        {
            // 영문자와 숫자를 제외한 모든 문자를 "_"로 교체
            var id = Regex.Replace(name, @"[^0-9A-Za-z_]", "_");

            if (id.Length == 0 || char.IsDigit(id[0])) id = "_" + id;
            return id;
        }

        private static void GenerateQuantumMenuSceneInfo()
        {
        }
    }
}