// <auto-generated> Generated from SceneListConfigSchema asset. Do not edit. </auto-generated>
using Eflatun.SceneReference;
using Quantum;
using QuantumUser.View;
using UnityEngine;
public static class SceneList
{
    public static readonly SceneInfo MenuPrototype = JsonUtility.FromJson<SceneInfo>(@"{""scene"":{""asset"":{""instanceID"":54848},""guid"":""21e27de20aca94240b1bcad8cc23e615""},""hasRuntimeConfig"":false,""runtimeConfig"":{""Seed"":0,""Map"":{""Id"":{""Value"":0}},""SimulationConfig"":{""Id"":{""Value"":0}},""SystemsConfig"":{""Id"":{""Value"":0}}}}");
    public static readonly SceneInfo MultiplayPrototype = JsonUtility.FromJson<SceneInfo>(@"{""scene"":{""asset"":{""instanceID"":54850},""guid"":""11cad2fe964a0424a84a5c9c3bfdb9e9""},""hasRuntimeConfig"":true,""runtimeConfig"":{""Seed"":0,""Map"":{""Id"":{""Value"":363481078872077106}},""SimulationConfig"":{""Id"":{""Value"":163983649200099817}},""SystemsConfig"":{""Id"":{""Value"":378553162747903325}}}}");

    public static readonly SceneInfo[] All = { MenuPrototype, MultiplayPrototype };

    /// <summary>
    /// 씬 식별자에 대응하는 씬 정보를 반환한다.
    /// </summary>
    public static SceneInfo Get(SceneId sceneId) => sceneId switch
    {
        SceneId.MenuPrototype => MenuPrototype,
        SceneId.MultiplayPrototype => MultiplayPrototype,
        _ => throw new System.ArgumentOutOfRangeException(nameof(sceneId)),
    };
}
