// <auto-generated> Generated from SceneListConfigSchema asset. Do not edit. </auto-generated>

namespace Yggdrasill.TestHelper.Protocol
{
    /// <summary>
    /// 씬의 식별자.
    /// </summary>
    public enum SceneId
    {
        MenuPrototype,
        MultiplayPrototype,
    }
}
