name: Unity CI
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  checks: write
jobs:
  unity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout non-lfs files
        uses: actions/checkout@v6
      - name: Setup Unity
        uses: ./.github/actions/setup-unity
      - name: Edit mode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Edit Mode Tests
      - name: Play mode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Play Mode Tests
  
  build:
    needs: unity-test
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        include:
          - targetPlatform: StandaloneWindows64
            buildProfile: 'Assets/Settings/Build Profiles/Windows.asset'
    steps:
      - name: Checkout non-lfs files
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildProfile: ${{ matrix.buildProfile }}