name: Unity CI
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  checks: write
jobs:
  unity-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout non-lfs files
        uses: actions/checkout@v6
      - name: Setup Unity
        uses: ./.github/actions/setup-unity
      - name: Edit&Play mode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Edit&Play Mode Tests
  
  development-build:
    needs: unity-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - targetPlatform: StandaloneWindows64
            buildProfile: 'Assets/Settings/Build Profiles/Windows-Development.asset'
            artifactName: Build-Windows-Development
            
    steps:
      - name: Checkout non-lfs files
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildProfile: ${{ matrix.buildProfile }}
          artifactName: ${{ matrix.artifactName }}

  e2e-test:
    needs: development-build
    runs-on: ${{ matrix.actionRunsOn }}
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - buildArtifactName: Build-Windows-Development
            executionFilePath: Yggdrasill.exe
            actionRunsOn: windows-latest
            testResultName: E2E-Test-Windows
    steps:
      - name: Checkout non-lfs files
        uses: actions/checkout@v6
      - name: E2E tests
        uses: ./.github/actions/e2e-test
        with:
          buildArtifactName: ${{ matrix.buildArtifactName }}
          executionFilePath: ${{ matrix.executionFilePath }}
          testResultName: ${{ matrix.testResultName }}